name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn --frozen-lockfile

      # Install project dependencies, test and build
      - name: Install dependencies
        run: cd frontend && yarn --frozen-lockfile
      - name: Run build
        run: cd frontend && yarn build --prod

      # Install project dependencies, test and build
      - name: Install dependencies
        run: cd server && yarn --frozen-lockfile

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          browser: chrome
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}