name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install

      # Install project dependencies, test and build
      - name: Install dependencies
        run: cd frontend && yarn --frozen-lockfile install
      - name: Run build
        run: cd frontend && yarn build --prod

      # Install project dependencies, test and build
      - name: Install dependencies
        run: cd server && yarn --frozen-lockfile install

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          browser: chrome